#!/bin/sh -xe
echo VERSION: ${VERSION:?}
echo JDK_HOME: ${JDK_HOME:?}
echo APP_HOME: ${APP_HOME:?}

. ../jdk-version.conf

rm -f formbuilder_win-$VERSION.zip
rm -rf formbuilder
mkdir formbuilder
cd formbuilder

tar xf $APP_HOME/formbuilder-$VERSION.tgz
mv formbuilder-$VERSION formbuilder 
mkdir app
mv formbuilder app/

tar xf $JDK_HOME/win/$JDK_VERSION.tgz
cp ../run.cmd .
cd ..

zip -r formbuilder_win-$VERSION.zip formbuilder
